[package]
name = "curl"
version = "1.0.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "3.0.7", features = ["derive"] }
log = "0.4.0"
env_logger = "0.8.4"